### ISSUE TITLE
Make the Elvis version configurable

### ISSUE THREAD

**Issue by andrei-mihaila** [inaka/elvis.mk#14]
The current version installs an old (6 years old) version of Elvis. It would be nice if it installed a newer version (at the user's choice).

Also, that old version of Elvis is a compiled one and doesn't work with Erlang/OTP 25.
```
$ make elvis
 DEP    elvis_mk (1.0.0)
 GEN    /redacted-path/elvis
=ERROR REPORT==== 5-Aug-2022::19:27:30.125393 ===
beam/beam_load.c(148): Error loading module elvis:
  please re-compile this module with an Erlang/OTP 25 compiler


escript: exception error: undefined function elvis:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
make: *** [/redacted-path/deps/elvis_mk/plugins.mk:36: elvis] Error 127
```
There is a fix in https://github.com/inaka/elvis.mk/pull/15 - but will probably need some improvements as it relies on `rebar3` being available.

**Comment by elbrujohalcon** [comment]
As stated in #15:
> @andrei-mihaila thanks for the pull request. The truth is we (https://github.com/inaka) are not actively maintaining this repo anymore. Since you seem to be an active user, do you want me to transfer it to your account so you can inherit and maintain it?

**Comment by andrei-mihaila** [comment]
To make the latest changes available via Erlang Mk you need to create a new tag (as the code tries to download a tag / release archive `https://github.com/inaka/elvis/archive/refs/tags/$(ELVIS_VERSION).tar.gz`).

**Comment by elbrujohalcon** [comment]
Done: https://github.com/inaka/elvis.mk/releases/tag/1.1.0
But I insist. Do you want to become the maintainer of this repo, @andrei-mihaila ?

**Comment by andrei-mihaila** [comment]
> As stated in #15:
> 
> > @andrei-mihaila thanks for the pull request. The truth is we (https://github.com/inaka) are not actively maintaining this repo anymore. Since you seem to be an active user, do you want me to transfer it to your account so you can inherit and maintain it?

Sorry, I don't have the Erlang experience nor the time availability for this. But thanks for the offer! And for the quick replies!

**Comment by andrei-mihaila** [comment]
Made some improvements in https://github.com/inaka/elvis.mk/pull/16, thanks @elbrujohalcon  for merging it. Please don't forget to create a tag / release (1.1.1?).
After that I think this would be resolved.

**Comment by elbrujohalcon** [comment]
Done.

**Comment by andrei-mihaila** [comment]
Thank you!
